<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<h3><a class="brand" href="index.php">Magna Utah Stake Sports</a></h3>
					<ul class="nav">
  						<li><a href="index.php">Home</a></li>
  						<li><a href="basketball.php">Basketball</a></li>
  						<li><a href="futsal.php">Futsal (indoor soccer)</a></li>
  						<li><a href="volleyball.php">Volleyball</a></li>
  						<li><a href="softball.php">Softball</a></li>
  						<li><a href="football.php">Flag Football</a></li>
  						<li><a href="5k.php">5K Run</a></li>
					</ul><!-- /nav -->
			</div><!-- /container -->
		</div> <!-- /navbar-inner -->
	</div><!-- /navbar -->